Allow returning arbitrary data from the handleAction function
knpwrs/redux-ts-utils pull request #7
Opened 2019-02-05 04:14 UTC by cinnabarcaracal

Useful for completely replacing the state when it makes more sense than modifying the current state. Acts as a sort of escape hatch for when more traditional reducer logic, including the use of higher-order array functions, is desired.

e.g.

```
handleAction(actions.storeFooArray, (draft, { payload }) => {
  return payload;
}),
handleAction(actions.storeUpdatedFooInArray, (draft, { payload }) => {
  return [...draft.filter(f => f.x !== payload.x), payload]
}),
```

2019-02-05 04:26 UTC, cinnabarcaracal commented
New PR updated for the new version. From my testing it is able to detect if you have also changed the draft, and will ignore any return value if that is the case. The return value `undefined` will be ignored (much like how immer ignores `undefined` return values)

I won't have time to add tests to this PR until later tonight, sorry.

2019-02-05 23:41 UTC, knpwrs requested changes

2019-02-05 23:41 UTC, knpwrs commented on src/handle-action.ts
> +      }
The else branch here is breaking the CI build: https://travis-ci.org/knpwrs/redux-ts-utils/jobs/488848467

2019-02-07 02:29 UTC, knpwrs requested changes
One more request -- could you add something to the `README` and maybe `example.ts`? Thanks!

2019-02-07 02:46 UTC, cinnabarcaracal commented
No problem, and happy to fix any issues with those

2019-02-10 01:59 UTC, knpwrs approved these changes

2019-02-10 01:59 UTC, merged

2019-02-10 02:12 UTC, knpwrs commented
Published as `3.1.0`. Thanks!